# Generated by Django 4.1.3 on 2022-12-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("noteapp", "0002_note_body_note_modified_note_title_note_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="modified",
        ),
    ]
